config/routes.rb
Rails.application.routes.draw do

  resources :shoppingbags
  get 'newsletters/new'

  resources :saveds do
    member do
      get :new
      post :new
    end
  end
  resources :products 
  
  resources :customers
  
  get 'sessions/new'

  get 'shop/home'

  get 'shop/help'

  get 'shop/kids'

  get 'shop/men'

  get 'shop/new_in'

  get 'shop/saved'

  get 'shop/women'

  get 'shop/all'

  get 'shop/shopping_bag'

  get 'customers/new'
  get '/signup', to: 'customers#new'
  post '/signup', to: 'customers#create'
  post 'saved/add'
  
  get '/saveds', to: 'saveds#index'
  
  get '/login', to: 'sessions#new' 
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  
  resources :newsletters
  
  post '/add', to: 'saveds#new'
  
  get '/save', to: 'saveds#create'
  post '/save', to: 'saveds#create'
  
  get '/newsletters', to: 'newsletters#new'
  post '/newsletters', to: 'newsletters#create'
  
  get '/shoppingbag', to: 'customers#shoppingbag'
  
  get '/home', to: "shop#home"
  
  
  root 'shop#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shoppingbag.rb
class Shoppingbag < ApplicationRecord
end

app/controllers/shoppingbags_controller.rb
class ShoppingbagsController < ApplicationController
  before_action :set_shoppingbag, only: %i[ show edit update destroy ]
  
  # GET /shoppingbags or /shoppingbags.json
  def index
    @shoppingbags = Shoppingbag.all
  end

  # GET /shoppingbags/1 or /shoppingbags/1.json
  def show
  end

  # GET /shoppingbags/new
  def new
    @shoppingbag = Shoppingbag.new
  end

  # GET /shoppingbags/1/edit
  def edit
  end

  # POST /shoppingbags or /shoppingbags.json
  def create
    @shoppingbag = Shoppingbag.new(shoppingbag_params)

    respond_to do |format|
      if @shoppingbag.save
        format.html { redirect_to '/shoppingbag', notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoppingbags/1 or /shoppingbags/1.json
  def update
    respond_to do |format|
      if @shoppingbag.update(shoppingbag_params)
        format.html { redirect_to @shoppingbag, notice: "Shoppingbag was successfully updated." }
        format.json { render :show, status: :ok, location: @shoppingbag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shoppingbag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoppingbags/1 or /shoppingbags/1.json
  def destroy
    @shoppingbag.destroy
    respond_to do |format|
      format.html { redirect_to '/shoppingbag', notice: "successfully" }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoppingbag
      @shoppingbag = Shoppingbag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shoppingbag_params
      params.require(:shoppingbag).permit(:customer_id, :product_name, :product_price, :color, :size, :quantity, :product_image)
    end
end

app/helpers/shoppingbags_helper.rb
module ShoppingbagsHelper
end

app/views/shoppingbags/_form.html.erb
<%= form_with(model: shoppingbag, local: true) do |form| %>
  <% if shoppingbag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoppingbag.errors.count, "error") %> prohibited this shoppingbag from being saved:</h2>

      <ul>
      <% shoppingbag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id, id: :shoppingbag_customer_id %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :shoppingbag_product_name %>
  </div>

  <div class="field">
    <%= form.label :product_price %>
    <%= form.text_field :product_price, id: :shoppingbag_product_price %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :shoppingbag_color %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :shoppingbag_size %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :shoppingbag_quantity %>
  </div>
  
  <div class="field">
    <%= form.label :product_image %>
    <%= form.text_field :product_image, id: :shoppingbag_product_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shoppingbags/edit.html.erb
<h1>Editing Shoppingbag</h1>

<%= render 'form', shoppingbag: @shoppingbag %>

<%= link_to 'Show', @shoppingbag %> |
<%= link_to 'Back', shoppingbags_path %>

app/views/shoppingbags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoppingbags</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Product name</th>
      <th>Product price</th>
      <th>Color</th>
      <th>Size</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoppingbags.each do |shoppingbag| %>
      <tr>
        <td><%= shoppingbag.customer_id %></td>
        <td><%= shoppingbag.product_name %></td>
        <td><%= shoppingbag.product_price %></td>
        <td><%= shoppingbag.color %></td>
        <td><%= shoppingbag.size %></td>
        <td><%= shoppingbag.quantity %></td>
        <td><%= link_to 'Show', shoppingbag %></td>
        <td><%= link_to 'Edit', edit_shoppingbag_path(shoppingbag) %></td>
        <td><%= link_to 'Destroy', shoppingbag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoppingbag', new_shoppingbag_path %>

app/views/shoppingbags/new.html.erb
<h1>New Shoppingbag</h1>

<%= render 'form', shoppingbag: @shoppingbag %>

<%= link_to 'Back', shoppingbags_path %>

app/views/shoppingbags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @shoppingbag.customer_id %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @shoppingbag.product_name %>
</p>

<p>
  <strong>Product price:</strong>
  <%= @shoppingbag.product_price %>
</p>

<p>
  <strong>Color:</strong>
  <%= @shoppingbag.color %>
</p>

<p>
  <strong>Size:</strong>
  <%= @shoppingbag.size %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @shoppingbag.quantity %>
</p>

<%= link_to 'Edit', edit_shoppingbag_path(@shoppingbag) %> |
<%= link_to 'Back', shoppingbags_path %>