config/routes.rb
Rails.application.routes.draw do

  resources :shoppingbags
  get 'newsletters/new'

  resources :saveds do
    member do
      get :new
      post :new
    end
  end
  resources :products 
  
  resources :customers
  
  get 'sessions/new'

  get 'shop/home'

  get 'shop/help'

  get 'shop/kids'

  get 'shop/men'

  get 'shop/new_in'

  get 'shop/saved'

  get 'shop/women'

  get 'shop/all'

  get 'shop/shopping_bag'

  get 'customers/new'
  get '/signup', to: 'customers#new'
  post '/signup', to: 'customers#create'
  post 'saved/add'
  
  get '/saveds', to: 'saveds#index'
  
  get '/login', to: 'sessions#new' 
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  
  resources :newsletters
  
  post '/add', to: 'saveds#new'
  
  get '/save', to: 'saveds#create'
  post '/save', to: 'saveds#create'
  
  get '/newsletters', to: 'newsletters#new'
  post '/newsletters', to: 'newsletters#create'
  
  get '/shoppingbag', to: 'customers#shoppingbag'
  
  get '/home', to: "shop#home"
  
  
  root 'shop#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  validates :email, presence: true, length: { maximum: 100 }, 
  format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i}, 
  uniqueness: { case_sensitive: false }
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: %i[ show edit update destroy ]

  # GET /newsletters or /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1 or /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters or /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)
    #newsletter = @newsletter
    respond_to do |format|
      if @newsletter.save
        #CustomerMailer.news(newsletter)
        format.html { redirect_to @newsletter, notice: "Newsletter was successfully created." }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1 or /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: "Newsletter was successfully updated." }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1 or /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: "Newsletter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_with(model: newsletter, local: true) do |form| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :newsletter_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<h1>Editing Newsletter</h1>

<%= render 'form', newsletter: @newsletter %>

<%= link_to 'Show', @newsletter %> |
<%= link_to 'Back', newsletters_path %>

app/views/newsletters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newsletters</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsletters.each do |newsletter| %>
      <tr>
        <td><%= newsletter.email %></td>
        <td><%= link_to 'Show', newsletter %></td>
        <td><%= link_to 'Edit', edit_newsletter_path(newsletter) %></td>
        <td><%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsletter', new_newsletter_path %>

app/views/newsletters/new.html.erb
<% provide(:title, 'newsletter') %>
<div class="center jumbotron">
<h1>subscribe</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
<%= form_for @newsletter do |form| %>
<%= render 'shared/error_email' %>
<%= form.label :email %>
<%= form.email_field :email, id: :newsletter_email , :style => "width:400px" %>
<%= form.submit 'subscribe' , :style => "width:100px"%>
</div>
<% end %>
 </div>
</div>
</div>

app/views/newsletters/show.html.erb
<div class="center jumbotron">
<h3>Thank you for subscribing</h3>
<p><%= @newsletter.email %></p>
</div>