config/routes.rb
Rails.application.routes.draw do

  resources :shoppingbags
  get 'newsletters/new'

  resources :saveds do
    member do
      get :new
      post :new
    end
  end
  resources :products 
  
  resources :customers
  
  get 'sessions/new'

  get 'shop/home'

  get 'shop/help'

  get 'shop/kids'

  get 'shop/men'

  get 'shop/new_in'

  get 'shop/saved'

  get 'shop/women'

  get 'shop/all'

  get 'shop/shopping_bag'

  get 'customers/new'
  get '/signup', to: 'customers#new'
  post '/signup', to: 'customers#create'
  post 'saved/add'
  
  get '/saveds', to: 'saveds#index'
  
  get '/login', to: 'sessions#new' 
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  
  resources :newsletters
  
  post '/add', to: 'saveds#new'
  
  get '/save', to: 'saveds#create'
  post '/save', to: 'saveds#create'
  
  get '/newsletters', to: 'newsletters#new'
  post '/newsletters', to: 'newsletters#create'
  
  get '/shoppingbag', to: 'customers#shoppingbag'
  
  get '/home', to: "shop#home"
  
  
  root 'shop#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  attr_accessor :remember_token
  has_many :shoppingbags
  
  before_save { self.email = email.downcase }
  validates :email, presence: true, length: { maximum: 100 }, 
  format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i}, 
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8, maximum: 20 }
  has_secure_password
  
  def Customer.digest(string) 
  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
  BCrypt::Engine.cost 
  BCrypt::Password.create(string, cost: cost) 
  end
  
  def Customer.new_token 
  SecureRandom.urlsafe_base64 
  end
 
  def remember
  self.remember_token = Customer.new_token
  update_attribute(:remember_digest, Customer.digest(remember_token))
  end
  
  def authenticated?(remember_token) 
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token) 
  end
  
  def forget 
  update_attribute(:remember_digest, nil) 
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :logged_in, only: [:edit, :update]
  before_action :correct_customer, only: [:edit, :update]
  
  def new
    @customer = Customer.new
  end
  
  def show
  @customer = Customer.find(params[:id])
  end
  
  def create
  @customer = Customer.new(customer_params)
  if @customer.save
    log_in @customer
    redirect_to @customer
  else 
    render 'new'
  end
  end
  
  def edit
  @customer = Customer.find(params[:id])
  end
  
  
  def update
  @customer = Customer.find(params[:id])
  if @customer.update_attributes(customer_params)
  flash[:success] = "Profile updated"
  redirect_to @customer
  else
  render 'edit'
  end
  end
  
  def logged_in
  unless logged_in?
  flash[:danger] = "Please log in."
  redirect_to login_url
  end
  end
  
  def correct_customer
  @customer = Customer.find(params[:id])
  redirect_to(root_url) unless @customer == current_customer
  end
  
  def shoppingbag
    @shoppingbags = Shoppingbag.where(customer_id: current_customer)
  end
  
  
  private
  def customer_params
  params.require(:customer).permit(:username, :email, :password, 
  :password_confirmation)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def gravatar_for(customer, size: 100)
  gravatar_id = Digest::MD5::hexdigest(customer.email.downcase)
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
  image_tag(gravatar_url, alt: customer.username, class: "gravatar")
  end
end

app/views/customers/edit.html.erb
<% provide(:title, "Edit Profile") %>
<div class="center jumbotron">
<h1>Customer Profile</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
 <%= form_for(@customer) do |f| %>
 <%= render 'shared/error_messages' %>
 <%= f.label :username %>
 <%= f.text_field :username, class: 'form-control' %>
 <%= f.label :email %>
 <%= f.email_field :email, class: 'form-control' %>
 <%= f.label :password %>
 <%= f.password_field :password, class: 'form-control' %>
 <%= f.label :password_confirmation, "Confirmation" %>
 <%= f.password_field :password_confirmation, class: 'form-control' %>
 <%= f.submit "Update Now", class: "btn btn-primary" %>
 <% end %>
 <div class="gravatar_edit">
 <%= gravatar_for @customer %>
 <a href="http://gravatar.com/emails" target="_blank">change</a>
 </div>
 </div>
</div>
</div>

app/views/customers/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="center jumbotron">
<h1>Sign up</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
 <%= form_for(@customer, url: signup_path) do |f| %>
 <%= render 'shared/error_messages' %>
 <%= f.label :username %>
 <%= f.text_field :username, class: 'form-control' %>
 <%= f.label :email %>
 <%= f.email_field :email, class: 'form-control'%>
 <%= f.label :password %>
 <%= f.password_field :password, class: 'form-control' %>
 <%= f.label :password_confirmation, "Confirmation" %>
 <%= f.password_field :password_confirmation, class: 'form-control' %>
 
 <%= f.submit "Submit", class: "btn btn-primary" %>
 <% end %>
 </div>
</div>
</div>

app/views/customers/shoppingbag.html.erb
<% provide(:title, 'Shopping bag') %>
<div class="center jumbotron">
<h1>Shoppingbags</h1>

    <div class="container">
    <% @shoppingbags.each do |shoppingbag| %>
    <div class="row" style="margin-top:30px" >
    <div class="col-xs-6">
    <%= image_tag(shoppingbag.product_image) %>
    </div>
    <div class="col-xs-6">
        <h3>Color<%= shoppingbag.product_name %></h3>
        <p>$<%= shoppingbag.product_price %></p>
        <h2>Color:<%= shoppingbag.color %></h2>
        <h2>Size<%= shoppingbag.size %></h2>
        <h2>Quantity:<%= shoppingbag.quantity %></h2>
        <h3><%= link_to 'Delete', shoppingbag, method: :delete, data: { confirm: 'Are you sure?' } %></h3>
        <h3><%= link_to 'Check out', shoppingbag, method: :delete, data: { confirm: 'Are you sure?' } %></h3>
    </div>
    </div>
    <% end %>
</div>
</div>

app/views/customers/show.html.erb
<% provide(:title, @customer.username) %>
<div class="center jumbotron">
<h3>
 <%= gravatar_for @customer %>
 <%= @customer.username %>
</h3>
<h3><%= link_to "Pending orders", '/shoppingbag' %></h3>
<h3><%= link_to "update login details", edit_customer_path(current_customer) %> </h3>
<h3><%= link_to "subscribe", {:controller => "newsletters", :action => "new"} %></h3>
</div>